version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/var/lib/app/
    ports:
      - "80:80"
    expose:
      - "80:80"
    environment:
      - POSTGRES_URI=postgres://user:password@postgres:5432/app
    depends_on:
      - postgres
    networks:
      - default
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    restart: unless-stopped
    volumes:
      #- data:/var/lib/postgresql/data/
      - ./src/sql/init.sql:/docker-entrypoint-initdb.d/0-init.sql
    ports:
      - "5432:5432"

volumes:
  data:

networks:
  default:
